In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/home-credit-default-risk/sample_submission.csv
/kaggle/input/competitions/home-credit-default-risk/bureau_balance.csv
/kaggle/input/competitions/home-credit-default-risk/POS_CASH_balance.csv
/kaggle/input/competitions/home-credit-default-risk/application_train.csv
/kaggle/input/competitions/home-credit-default-risk/HomeCredit_columns_description.csv
/kaggle/input/competitions/home-credit-default-risk/application_test.csv
/kaggle/input/competitions/home-credit-default-risk/previous_application.csv
/kaggle/input/competitions/home-credit-default-risk/credit_card_balance.csv
/kaggle/input/competitions/home-credit-default-risk/installments_payments.csv
/kaggle/input/competitions/home-credit-default-risk/bureau.csv

In [2]:
#ライブラリの読み込み
import numpy as np
import pandas as pd
import re
import pickle
import gc

# scikit-learn
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

# LightGBM
# !pip install lightgbm==3.2.1  #LightGBMバージョン指定（書籍の再現性のため）
import lightgbm as lgb

import warnings
warnings.filterwarnings("ignore")

In [3]:
#ファイルの読み込み・データ確認
application_train = pd.read_csv("/kaggle/input/competitions/home-credit-default-risk/application_train.csv")
print(application_train.shape)
display(application_train.head())

application_test = pd.read_csv("/kaggle/input/competitions/home-credit-default-risk/application_test.csv")
print(application_test.shape)
display(application_test.head())

(307511, 122)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

(48744, 121)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#メモリ削除の為の関数
def reduce_mem_usage(df):
    start_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        else:
            pass

    end_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))
    
    return df

In [5]:
#メモリ削除の実行
application_train = reduce_mem_usage(application_train)
application_test = reduce_mem_usage(application_test)

Memory usage of dataframe is 286.23 MB
Memory usage after optimization is: 92.38 MB
Decreased by 67.7%
Memory usage of dataframe is 45.00 MB
Memory usage after optimization is: 14.60 MB
Decreased by 67.6%

In [6]:
#データの確認
display(application_train["DAYS_EMPLOYED"].value_counts())
print("正の値の割合: {:.4f}".format((application_train["DAYS_EMPLOYED"]>0).mean()))
print("正の値の個数: {}".format((application_train["DAYS_EMPLOYED"]>0).sum()))
# -> 正の値が18%。しかもすべて8割が365243と同一値。働き始めてからの日数をマイナス表記しているためこれは欠損と判断。

DAYS_EMPLOYED
 365243    55374
-200         156
-224         152
-230         151
-199         151
           ...
-11471         1
-12878         1
-10573         1
-12990         1
-14184         1
Name: count, Length: 12574, dtype: int64

正の値の割合: 0.1801
正の値の個数: 55374

In [7]:
#欠損値の対処
application_train["DAYS_EMPLOYED"] = application_train["DAYS_EMPLOYED"].replace(365243, np.nan)
application_test["DAYS_EMPLOYED"] = application_test["DAYS_EMPLOYED"].replace(365243, np.nan)

In [8]:
#仮説に基づく特徴量生成
# 特徴量1: 総所得金額を世帯人数で割った値
application_train['INCOME_div_PERSON'] = application_train['AMT_INCOME_TOTAL'] / application_train['CNT_FAM_MEMBERS']

# 特徴量2: 総所得金額を就労期間で割った値
application_train['INCOME_div_EMPLOYED'] = application_train['AMT_INCOME_TOTAL'] / application_train['DAYS_EMPLOYED']

# 特徴量3: 外部スコアの平均値など
application_train["EXT_SOURCE_mean"] = application_train[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].mean(axis=1)
application_train["EXT_SOURCE_max"] = application_train[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].max(axis=1)
application_train["EXT_SOURCE_min"] = application_train[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].min(axis=1)
application_train["EXT_SOURCE_std"] = application_train[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].std(axis=1)
application_train["EXT_SOURCE_count"] = application_train[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].notnull().sum(axis=1)

# 特徴量4: 就労期間を年齢で割った値 (年齢に占める就労期間の割合)
application_train['DAYS_EMPLOYED_div_BIRTH'] = application_train['DAYS_EMPLOYED'] / application_train['DAYS_BIRTH']

# 特徴量5: 年金支払額を所得金額で割った値
application_train['ANNUITY_div_INCOME'] = application_train['AMT_ANNUITY'] / application_train['AMT_INCOME_TOTAL']

# 特徴量6: 年金支払額を借入金で割った値
application_train['ANNUITY_div_CREDIT'] = application_train['AMT_ANNUITY'] / application_train['AMT_CREDIT']

#testにも同じ特徴量を追加
application_test['INCOME_div_PERSON'] = application_test['AMT_INCOME_TOTAL'] / application_test['CNT_FAM_MEMBERS']
application_test['INCOME_div_EMPLOYED'] = application_test['AMT_INCOME_TOTAL'] / application_test['DAYS_EMPLOYED']
application_test["EXT_SOURCE_mean"] = application_test[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].mean(axis=1)
application_test["EXT_SOURCE_max"] = application_test[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].max(axis=1)
application_test["EXT_SOURCE_min"] = application_test[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].min(axis=1)
application_test["EXT_SOURCE_std"] = application_test[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].std(axis=1)
application_test["EXT_SOURCE_count"] = application_test[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].notnull().sum(axis=1)
application_test['DAYS_EMPLOYED_div_BIRTH'] = application_test['DAYS_EMPLOYED'] / application_test['DAYS_BIRTH']
application_test['ANNUITY_div_INCOME'] = application_test['AMT_ANNUITY'] / application_test['AMT_INCOME_TOTAL']
application_test['ANNUITY_div_CREDIT'] = application_test['AMT_ANNUITY'] / application_test['AMT_CREDIT']

In [9]:
#データセットの作成
x_train = application_train.drop(columns=["TARGET", "SK_ID_CURR"])
y_train = application_train["TARGET"]
id_train = application_train[["SK_ID_CURR"]]

x_test = application_test.drop(columns=["SK_ID_CURR" ])
id_test = application_test[["SK_ID_CURR"]]

In [10]:
#カテゴリー変数をカテゴリー型に変換
for col in x_train.columns:
    if x_train[col].dtype=="O":
        x_train[col] = x_train[col].astype("category")

for col in x_test.columns:
    if x_test[col].dtype=="O":
        x_test[col] = x_test[col].astype("category")

In [11]:
#目的変数の1の割合とそれぞれの件数の確認
print("mean: {:.4f}".format(y_train.mean()))
y_train.value_counts()

mean: 0.0807

TARGET
0    282686
1     24825
Name: count, dtype: int64

In [12]:
#学習関数の定義
def train_lgb(input_x,
              input_y,
              input_id,
              params,
              list_nfold=[0,1,2,3,4],
              n_splits=5,
             ):
    train_oof = np.zeros(len(input_x))
    metrics = []
    imp = pd.DataFrame()

    # cross-validation
    cv = list(StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=123).split(input_x, input_y))
    for nfold in list_nfold:
        print("-"*20, nfold, "-"*20)
        
        # make dataset
        idx_tr, idx_va = cv[nfold][0], cv[nfold][1]
        x_tr, y_tr, id_tr = input_x.loc[idx_tr, :], input_y[idx_tr], input_id.loc[idx_tr, :]
        x_va, y_va, id_va = input_x.loc[idx_va, :], input_y[idx_va], input_id.loc[idx_va, :]
        print(x_tr.shape, x_va.shape)
        
        # train
        model = lgb.LGBMClassifier(**params)
        
        
        # # 2024/02/14環境で動かしたい場合はこのコードを利用してください。
        model.fit(x_tr,
                  y_tr,
                  eval_set=[(x_tr,y_tr), (x_va,y_va)],
                  callbacks=[
                      lgb.early_stopping(stopping_rounds=100, verbose=True),
                      lgb.log_evaluation(100),
                  ],
                 )
        
        fname_lgb = "model_lgb_fold{}.pickle".format(nfold)
        with open(fname_lgb, "wb") as f:
            pickle.dump(model, f, protocol=4)
        
        # evaluate
        y_tr_pred = model.predict_proba(x_tr)[:,1]
        y_va_pred = model.predict_proba(x_va)[:,1]
        metric_tr = roc_auc_score(y_tr, y_tr_pred)
        metric_va = roc_auc_score(y_va, y_va_pred)
        metrics.append([nfold, metric_tr, metric_va])
        print("[auc] tr:{:.4f}, va:{:.4f}".format(metric_tr, metric_va))
        
        # oof
        train_oof[idx_va] = y_va_pred
        
        # imp
        _imp = pd.DataFrame({"col":input_x.columns, "imp":model.feature_importances_, "nfold":nfold})
        imp = pd.concat([imp, _imp])
      
    print("-"*20, "result", "-"*20)
    # metric
    metrics = np.array(metrics)
    print(metrics)
    print("[cv] tr:{:.4f}+-{:.4f}, va:{:.4f}+-{:.4f}".format(
        metrics[:,1].mean(), metrics[:,1].std(),
        metrics[:,2].mean(), metrics[:,2].std(),
    ))
    print("[oof] {:.4f}".format(
        roc_auc_score(input_y, train_oof)
    ))
    
    # oof
    train_oof = pd.concat([
        input_id,
        pd.DataFrame({"pred":train_oof})
    ], axis=1)
    
    # importance
    imp = imp.groupby("col")["imp"].agg(["mean", "std"]).reset_index(drop=False)
    imp.columns = ["col", "imp", "imp_std"]
    
    return train_oof, imp, metrics

In [13]:
# ハイパーパラメータの設定
params = {
    'boosting_type': 'gbdt',
    'objective': 'binary', 
    'metric': 'auc',
    'learning_rate': 0.05,
    'num_leaves': 32,
    'n_estimators': 100000,
    "random_state": 123,
    "importance_type": "gain",
}

# 学習の実行
train_oof, imp, metrics = train_lgb(x_train,
                                    y_train,
                                    id_train,
                                    params,
                                    list_nfold=[0,1,2,3,4],
                                    n_splits=5,
                                   )

-------------------- 0 --------------------
(246008, 130) (61503, 130)
[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.104215 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13680
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 126
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.787895	valid_1's auc: 0.761408
[200]	training's auc: 0.81693	valid_1's auc: 0.765243
[300]	training's auc: 0.838558	valid_1's auc: 0.765348
Early stopping, best iteration is:
[217]	training's auc: 0.820432	valid_1's auc: 0.765606
[auc] tr:0.8204, va:0.7656
-------------------- 1 --------------------
(246009, 130) (61502, 130)
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.098808 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13620
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 125
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.788443	valid_1's auc: 0.762499
[200]	training's auc: 0.816996	valid_1's auc: 0.766959
[300]	training's auc: 0.838705	valid_1's auc: 0.767169
[400]	training's auc: 0.856102	valid_1's auc: 0.767313
Early stopping, best iteration is:
[350]	training's auc: 0.847134	valid_1's auc: 0.767572
[auc] tr:0.8471, va:0.7676
-------------------- 2 --------------------
(246009, 130) (61502, 130)
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.101744 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13632
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 126
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.787758	valid_1's auc: 0.763571
[200]	training's auc: 0.817101	valid_1's auc: 0.766396
[300]	training's auc: 0.838922	valid_1's auc: 0.766773
Early stopping, best iteration is:
[245]	training's auc: 0.827656	valid_1's auc: 0.76685
[auc] tr:0.8277, va:0.7669
-------------------- 3 --------------------
(246009, 130) (61502, 130)
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.102197 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13615
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 126
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.78857	valid_1's auc: 0.760798
[200]	training's auc: 0.818476	valid_1's auc: 0.764382
[300]	training's auc: 0.839467	valid_1's auc: 0.764923
[400]	training's auc: 0.857551	valid_1's auc: 0.76473
Early stopping, best iteration is:
[320]	training's auc: 0.843551	valid_1's auc: 0.765029
[auc] tr:0.8436, va:0.7650
-------------------- 4 --------------------
(246009, 130) (61502, 130)
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.102489 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13688
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 125
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.789403	valid_1's auc: 0.756032
[200]	training's auc: 0.817693	valid_1's auc: 0.760304
[300]	training's auc: 0.838031	valid_1's auc: 0.760646
[400]	training's auc: 0.855589	valid_1's auc: 0.761107
Early stopping, best iteration is:
[376]	training's auc: 0.851284	valid_1's auc: 0.761288
[auc] tr:0.8513, va:0.7613
-------------------- result --------------------
[[0.         0.82043204 0.76560606]
 [1.         0.84713373 0.76757212]
 [2.         0.8276559  0.76685003]
 [3.         0.84355104 0.76502904]
 [4.         0.85128418 0.76128783]]
[cv] tr:0.8380+-0.0119, va:0.7653+-0.0022
[oof] 0.7652

In [14]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:10]

                    col            imp      imp_std
44      EXT_SOURCE_mean  113116.122069  1786.948047
10   ANNUITY_div_CREDIT   22151.650249   898.087993
112   ORGANIZATION_TYPE   20187.355369  1438.208866
41         EXT_SOURCE_3   10549.221250  1015.861249
24           DAYS_BIRTH    6863.921363   709.067033
45       EXT_SOURCE_min    6826.756135   440.769525
39         EXT_SOURCE_1    6085.678020   796.181708
0           AMT_ANNUITY    5342.644769   621.544562
2       AMT_GOODS_PRICE    5332.378775   472.867742
1            AMT_CREDIT    4722.058802   766.762029

In [15]:
#推論関数の定義
def predict_lgb(input_x,
                input_id,
                list_nfold=[0,1,2,3,4],
               ):
    pred = np.zeros((len(input_x), len(list_nfold)))
    for nfold in list_nfold:
        print("-"*20, nfold, "-"*20)
        fname_lgb = "model_lgb_fold{}.pickle".format(nfold)
        with open(fname_lgb, "rb") as f:
            model = pickle.load(f)
        pred[:, nfold] = model.predict_proba(input_x)[:,1]
    
    pred = pd.concat([
        input_id,
        pd.DataFrame({"pred": pred.mean(axis=1)}),
    ], axis=1)
    
    print("Done.")
    
    return pred

In [16]:
#推論処理の実行
test_pred = predict_lgb(x_test,
                        id_test,
                        list_nfold=[0,1,2,3,4],
                       )

-------------------- 0 --------------------
-------------------- 1 --------------------
-------------------- 2 --------------------
-------------------- 3 --------------------
-------------------- 4 --------------------
Done.

In [17]:
#提出ファイルの作成
df_submit = test_pred.rename(columns={"pred":"TARGET"})
print(df_submit.shape)
display(df_submit.head())

# ファイル出力
df_submit.to_csv("submission_baseline.csv", index=None)

(48744, 2)

   SK_ID_CURR    TARGET
0      100001  0.033575
1      100005  0.113764
2      100013  0.019663
3      100028  0.042029
4      100038  0.180636

In [18]:
#POS_CASH_balance.csvファイル読み込み
pos = pd.read_csv("/kaggle/input/competitions/home-credit-default-risk/POS_CASH_balance.csv")
pos = reduce_mem_usage(pos)
print(pos.shape)
pos.head()

Memory usage of dataframe is 610.43 MB
Memory usage after optimization is: 238.45 MB
Decreased by 60.9%
(10001358, 8)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0

In [19]:
#カテゴリ変数をone-hot-encodingで数値に変換
pos_ohe = pd.get_dummies(pos, columns=["NAME_CONTRACT_STATUS"], dummy_na=True)
col_ohe = sorted(list(set(pos_ohe.columns) - set(pos.columns)))
print(len(col_ohe))
col_ohe

10

['NAME_CONTRACT_STATUS_Active',
 'NAME_CONTRACT_STATUS_Amortized debt',
 'NAME_CONTRACT_STATUS_Approved',
 'NAME_CONTRACT_STATUS_Canceled',
 'NAME_CONTRACT_STATUS_Completed',
 'NAME_CONTRACT_STATUS_Demand',
 'NAME_CONTRACT_STATUS_Returned to the store',
 'NAME_CONTRACT_STATUS_Signed',
 'NAME_CONTRACT_STATUS_XNA',
 'NAME_CONTRACT_STATUS_nan']

In [20]:
#SK_ID_CURRをキーに集約処理
pos_ohe_agg = pos_ohe.groupby("SK_ID_CURR").agg(
    {
        # 数値の集約
        "MONTHS_BALANCE": ["mean", "std", "min", "max"],
        "CNT_INSTALMENT": ["mean", "std", "min", "max"],
        "CNT_INSTALMENT_FUTURE": ["mean", "std", "min", "max"],
        "SK_DPD": ["mean", "std", "min", "max"],
        "SK_DPD_DEF": ["mean", "std", "min", "max"],
        # カテゴリ変数をone-hot-encodingした値の集約
        "NAME_CONTRACT_STATUS_Active": ["mean"],
        "NAME_CONTRACT_STATUS_Amortized debt": ["mean"],
        "NAME_CONTRACT_STATUS_Approved": ["mean"],
        "NAME_CONTRACT_STATUS_Canceled": ["mean"],
        "NAME_CONTRACT_STATUS_Completed": ["mean"],
        "NAME_CONTRACT_STATUS_Demand": ["mean"],
        "NAME_CONTRACT_STATUS_Returned to the store": ["mean"],
        "NAME_CONTRACT_STATUS_Signed": ["mean"],
        "NAME_CONTRACT_STATUS_XNA": ["mean"],
        "NAME_CONTRACT_STATUS_nan": ["mean"],
        # IDのユニーク数をカウント (ついでにレコード数もカウント)
        "SK_ID_PREV":["count", "nunique"],
    }
)

# カラム名の付与
pos_ohe_agg.columns = [i + "_" + j for i,j in pos_ohe_agg.columns]
pos_ohe_agg = pos_ohe_agg.reset_index(drop=False)

print(pos_ohe_agg.shape)
pos_ohe_agg.head()

(337252, 33)

,SK_ID_CURR,MONTHS_BALANCE_mean,MONTHS_BALANCE_std,MONTHS_BALANCE_min,MONTHS_BALANCE_max,CNT_INSTALMENT_mean,CNT_INSTALMENT_std,CNT_INSTALMENT_min,CNT_INSTALMENT_max,CNT_INSTALMENT_FUTURE_mean,...,NAME_CONTRACT_STATUS_Approved_mean,NAME_CONTRACT_STATUS_Canceled_mean,NAME_CONTRACT_STATUS_Completed_mean,NAME_CONTRACT_STATUS_Demand_mean,NAME_CONTRACT_STATUS_Returned to the store_mean,NAME_CONTRACT_STATUS_Signed_mean,NAME_CONTRACT_STATUS_XNA_mean,NAME_CONTRACT_STATUS_nan_mean,SK_ID_PREV_count,SK_ID_PREV_nunique
0,100001,-72.555556,20.863312,-96,-53,4.000000,0.000000,4.0,4.0,1.444444,...,0.0,0.0,0.222222,0.0,0.0,0.000000,0.0,0.0,9,2
1,100002,-10.000000,5.627314,-19,-1,24.000000,0.000000,24.0,24.0,15.000000,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,19,1
2,100003,-43.785714,24.640162,-77,-18,10.107142,2.806597,6.0,12.0,5.785714,...,0.0,0.0,0.071429,0.0,0.0,0.000000,0.0,0.0,28,3
3,100004,-25.500000,1.290994,-27,-24,3.750000,0.500000,3.0,4.0,2.250000,...,0.0,0.0,0.250000,0.0,0.0,0.000000,0.0,0.0,4,1
4,100005,-20.000000,3.316625,-25,-15,11.700000,0.948683,9.0,12.0,7.200000,...,0.0,0.0,0.090909,0.0,0.0,0.090909,0.0,0.0,11,1

In [21]:
#SK_ID_CURRをキーにして結合
df_train = pd.merge(application_train, pos_ohe_agg, on="SK_ID_CURR", how="left")
print(df_train.shape)
display(df_train.head())

df_test =  pd.merge(application_test, pos_ohe_agg, on="SK_ID_CURR", how="left")
print(df_test.shape)
display(df_test.head())

(307511, 164)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,NAME_CONTRACT_STATUS_Approved_mean,NAME_CONTRACT_STATUS_Canceled_mean,NAME_CONTRACT_STATUS_Completed_mean,NAME_CONTRACT_STATUS_Demand_mean,NAME_CONTRACT_STATUS_Returned to the store_mean,NAME_CONTRACT_STATUS_Signed_mean,NAME_CONTRACT_STATUS_XNA_mean,NAME_CONTRACT_STATUS_nan_mean,SK_ID_PREV_count,SK_ID_PREV_nunique
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,19.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.0,0.0,0.071429,0.0,0.000000,0.000000,0.0,0.0,28.0,3.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.0,0.0,0.250000,0.0,0.000000,0.000000,0.0,0.0,4.0,1.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.0,0.0,0.095238,0.0,0.047619,0.000000,0.0,0.0,21.0,3.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.0,0.0,0.045455,0.0,0.000000,0.015152,0.0,0.0,66.0,5.0

(48744, 163)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,NAME_CONTRACT_STATUS_Approved_mean,NAME_CONTRACT_STATUS_Canceled_mean,NAME_CONTRACT_STATUS_Completed_mean,NAME_CONTRACT_STATUS_Demand_mean,NAME_CONTRACT_STATUS_Returned to the store_mean,NAME_CONTRACT_STATUS_Signed_mean,NAME_CONTRACT_STATUS_XNA_mean,NAME_CONTRACT_STATUS_nan_mean,SK_ID_PREV_count,SK_ID_PREV_nunique
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0.0,0.0,0.222222,0.0,0.0,0.000000,0.0,0.0,9.0,2.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0.0,0.0,0.090909,0.0,0.0,0.090909,0.0,0.0,11.0,1.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0.0,0.0,0.083333,0.0,0.0,0.027778,0.0,0.0,36.0,3.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0.0,0.0,0.064516,0.0,0.0,0.000000,0.0,0.0,31.0,2.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0.0,0.0,0.076923,0.0,0.0,0.000000,0.0,0.0,13.0,1.0

In [22]:
#データセットの作成
x_train = df_train.drop(columns=["TARGET", "SK_ID_CURR"])
y_train = df_train["TARGET"]
id_train = df_train[["SK_ID_CURR"]]

x_test = df_test.drop(columns=["SK_ID_CURR" ])
id_test = df_test[["SK_ID_CURR"]]

#カテゴリー変数をカテゴリー型に変換
for col in x_train.columns:
    if x_train[col].dtype=="O":
        x_train[col] = x_train[col].astype("category")

for col in x_test.columns:
    if x_test[col].dtype=="O":
        x_test[col] = x_test[col].astype("category")

In [23]:
#モデル学習
train_oof, imp, metrics = train_lgb(x_train,
                                    y_train,
                                    id_train,
                                    params,
                                    list_nfold=[0,1,2,3,4],
                                    n_splits=5,
                                   )

-------------------- 0 --------------------
(246008, 162) (61503, 162)
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.129279 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18345
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 158
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.794991	valid_1's auc: 0.765644
[200]	training's auc: 0.825333	valid_1's auc: 0.770975
[300]	training's auc: 0.848237	valid_1's auc: 0.770965
Early stopping, best iteration is:
[201]	training's auc: 0.825675	valid_1's auc: 0.771035
[auc] tr:0.8257, va:0.7710
-------------------- 1 --------------------
(246009, 162) (61502, 162)
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.126182 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18305
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 157
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.795051	valid_1's auc: 0.769807
[200]	training's auc: 0.824857	valid_1's auc: 0.775138
[300]	training's auc: 0.84745	valid_1's auc: 0.776032
[400]	training's auc: 0.865044	valid_1's auc: 0.77622
Early stopping, best iteration is:
[385]	training's auc: 0.862517	valid_1's auc: 0.776397
[auc] tr:0.8625, va:0.7764
-------------------- 2 --------------------
(246009, 162) (61502, 162)
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.128987 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18303
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 158
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.795129	valid_1's auc: 0.769416
[200]	training's auc: 0.825398	valid_1's auc: 0.772886
[300]	training's auc: 0.847407	valid_1's auc: 0.773233
[400]	training's auc: 0.864993	valid_1's auc: 0.773724
Early stopping, best iteration is:
[386]	training's auc: 0.8626	valid_1's auc: 0.773819
[auc] tr:0.8626, va:0.7738
-------------------- 3 --------------------
(246009, 162) (61502, 162)
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.131442 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18276
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 158
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.794661	valid_1's auc: 0.765985
[200]	training's auc: 0.82547	valid_1's auc: 0.77062
[300]	training's auc: 0.847119	valid_1's auc: 0.771755
[400]	training's auc: 0.865691	valid_1's auc: 0.771724
Early stopping, best iteration is:
[356]	training's auc: 0.857771	valid_1's auc: 0.772077
[auc] tr:0.8578, va:0.7721
-------------------- 4 --------------------
(246009, 162) (61502, 162)
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.127524 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18349
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 157
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.79618	valid_1's auc: 0.761253
[200]	training's auc: 0.82638	valid_1's auc: 0.765554
[300]	training's auc: 0.849087	valid_1's auc: 0.766346
Early stopping, best iteration is:
[299]	training's auc: 0.848908	valid_1's auc: 0.766379
[auc] tr:0.8489, va:0.7664
-------------------- result --------------------
[[0.         0.82567537 0.77103521]
 [1.         0.86251654 0.77639663]
 [2.         0.8626001  0.77381905]
 [3.         0.8577705  0.77207711]
 [4.         0.84890753 0.76637895]]
[cv] tr:0.8515+-0.0138, va:0.7719+-0.0033
[oof] 0.7719

In [24]:
#説明変数の重要度の確認
imp.sort_values("imp", ascending=False)[:10]

                            col            imp      imp_std
52              EXT_SOURCE_mean  112315.659897  1299.621166
134           ORGANIZATION_TYPE   20726.497624  1751.268629
10           ANNUITY_div_CREDIT   18006.583582   916.359982
49                 EXT_SOURCE_3   10148.394658  1038.519610
53               EXT_SOURCE_min    6923.783037   274.631043
32                   DAYS_BIRTH    6506.565764   879.929487
47                 EXT_SOURCE_1    6081.699955   755.262038
21   CNT_INSTALMENT_FUTURE_mean    5973.264411   686.773436
108          MONTHS_BALANCE_std    5311.481420   574.307947
0                   AMT_ANNUITY    5193.704381   551.231370

In [25]:
#推論処理
test_pred = predict_lgb(x_test,
                        id_test,
                        list_nfold=[0,1,2,3,4],
                       )

-------------------- 0 --------------------
-------------------- 1 --------------------
-------------------- 2 --------------------
-------------------- 3 --------------------
-------------------- 4 --------------------
Done.

In [26]:
#提出ファイルの作成
df_submit = test_pred.rename(columns={"pred":"TARGET"})
print(df_submit.shape)
display(df_submit.head())

# ファイル出力
df_submit.to_csv("submission_baseline2.csv", index=None)

(48744, 2)

   SK_ID_CURR    TARGET
0      100001  0.037486
1      100005  0.104732
2      100013  0.029330
3      100028  0.043877
4      100038  0.213274

In [27]:
#optunaライブラリの読み込み
import optuna

In [28]:
#データセットの作成
x_train = df_train.drop(columns=["TARGET", "SK_ID_CURR"])
y_train = df_train["TARGET"]
id_train = df_train[["SK_ID_CURR"]]

x_test = df_test.drop(columns=["SK_ID_CURR" ])
id_test = df_test[["SK_ID_CURR"]]

#カテゴリー変数をカテゴリー型に変換
for col in x_train.columns:
    if x_train[col].dtype=="O":
        x_train[col] = x_train[col].astype("category")

for col in x_test.columns:
    if x_test[col].dtype=="O":
        x_test[col] = x_test[col].astype("category")

In [29]:
# 探索しないハイパーパラメータ
params_base = {
    "boosting_type": "gbdt",
    "objective": "binary",
    "metric": "auc",
    "verbosity": -1,
    "learning_rate": 0.05,
    "n_estimators": 100000,
    "bagging_freq": 1,
    "random_state": 123,
}

# 目的関数の定義
def objective(trial):
    # 探索するハイパーパラメータ
    params_tuning = {
        "num_leaves": trial.suggest_int("num_leaves", 8, 256),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 200),
        "min_sum_hessian_in_leaf": trial.suggest_float("min_sum_hessian_in_leaf", 1e-5, 1e-2, log=True),
        "feature_fraction": trial.suggest_float("feature_fraction", 0.5, 1.0),
        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.5, 1.0),
        "lambda_l1": trial.suggest_float("lambda_l1", 1e-2, 1e+2, log=True),
        "lambda_l2": trial.suggest_float("lambda_l2", 1e-2, 1e+2, log=True),
    }
    params_tuning.update(params_base)
    
    # モデル学習・評価
    list_metrics = []
    cv = list(StratifiedKFold(n_splits=5, shuffle=True, random_state=123).split(x_train, y_train))
    list_fold = [0]  # 処理高速化のために1つめのfoldのみとする。
    for nfold in list_fold:
        idx_tr, idx_va = cv[nfold][0], cv[nfold][1]
        x_tr, y_tr = x_train.loc[idx_tr, :], y_train[idx_tr]
        x_va, y_va = x_train.loc[idx_va, :], y_train[idx_va]
        model = lgb.LGBMClassifier(**params_tuning)
        
        
#         # 2024/02/14環境で動かしたい場合はこのコードを利用してください。
        model.fit(x_tr,
                  y_tr,
                  eval_set=[(x_tr,y_tr), (x_va,y_va)],
                  callbacks=[
                      lgb.early_stopping(stopping_rounds=100, verbose=True),
                      lgb.log_evaluation(0),
                  ],
                 )
        
        y_va_pred = model.predict_proba(x_va)[:,1]
        metric_va = roc_auc_score(y_va, y_va_pred) # 評価指標をAUCにする
        list_metrics.append(metric_va)
    
    # 評価指標の算出
    metrics = np.mean(list_metrics)
    
    return metrics

In [30]:
sampler = optuna.samplers.TPESampler(seed=123)
study = optuna.create_study(sampler=sampler, direction="maximize")
study.optimize(objective, n_trials=50, n_jobs=5)

[I 2026-04-15 06:37:14,848] A new study created in memory with name: no-name-4e37a508-2248-48bb-8102-80854412d457

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[166]	training's auc: 0.933914	valid_1's auc: 0.769429

[I 2026-04-15 06:40:54,078] Trial 2 finished with value: 0.769429132442432 and parameters: {'num_leaves': 234, 'min_child_samples': 74, 'min_sum_hessian_in_leaf': 0.00013554711379089323, 'feature_fraction': 0.8556156406694722, 'bagging_fraction': 0.8527021013253097, 'lambda_l1': 4.134878565389124, 'lambda_l2': 0.04788656630079208}. Best is trial 2 with value: 0.769429132442432.

Early stopping, best iteration is:
[162]	training's auc: 0.901782	valid_1's auc: 0.767268

[I 2026-04-15 06:41:00,787] Trial 0 finished with value: 0.7672683242351916 and parameters: {'num_leaves': 209, 'min_child_samples': 35, 'min_sum_hessian_in_leaf': 0.0001464230627154055, 'feature_fraction': 0.8306052048121111, 'bagging_fraction': 0.5551141279331493, 'lambda_l1': 0.018750746169413617, 'lambda_l2': 11.391881325211362}. Best is trial 2 with value: 0.769429132442432.

Early stopping, best iteration is:
[576]	training's auc: 0.83301	valid_1's auc: 0.770263
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2026-04-15 06:41:14,493] Trial 3 finished with value: 0.7702626475462304 and parameters: {'num_leaves': 136, 'min_child_samples': 104, 'min_sum_hessian_in_leaf': 0.0002011255258313497, 'feature_fraction': 0.659726982311863, 'bagging_fraction': 0.6064933695818217, 'lambda_l1': 60.033875120762325, 'lambda_l2': 0.06009033487607506}. Best is trial 3 with value: 0.7702626475462304.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[303]	training's auc: 0.883808	valid_1's auc: 0.77126
Early stopping, best iteration is:
[278]	training's auc: 0.909815	valid_1's auc: 0.771214

[I 2026-04-15 06:41:42,754] Trial 4 finished with value: 0.7712597970362206 and parameters: {'num_leaves': 170, 'min_child_samples': 25, 'min_sum_hessian_in_leaf': 2.347530015128527e-05, 'feature_fraction': 0.5224766350860123, 'bagging_fraction': 0.9861926988268999, 'lambda_l1': 18.352839027705517, 'lambda_l2': 30.6132237732373}. Best is trial 4 with value: 0.7712597970362206.
[I 2026-04-15 06:41:48,424] Trial 1 finished with value: 0.7712140988190815 and parameters: {'num_leaves': 211, 'min_child_samples': 176, 'min_sum_hessian_in_leaf': 0.00018119921980586337, 'feature_fraction': 0.6332254618798151, 'bagging_fraction': 0.8151196860237276, 'lambda_l1': 0.8556109011652145, 'lambda_l2': 63.551585442152806}. Best is trial 4 with value: 0.7712597970362206.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[474]	training's auc: 0.845137	valid_1's auc: 0.773424

[I 2026-04-15 06:44:05,621] Trial 5 finished with value: 0.7734238220730583 and parameters: {'num_leaves': 29, 'min_child_samples': 181, 'min_sum_hessian_in_leaf': 0.009603130096991557, 'feature_fraction': 0.7596240020970275, 'bagging_fraction': 0.6378446563284961, 'lambda_l1': 0.9224448708224339, 'lambda_l2': 6.26673008652325}. Best is trial 5 with value: 0.7734238220730583.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[270]	training's auc: 0.877123	valid_1's auc: 0.770913

[I 2026-04-15 06:44:25,034] Trial 9 finished with value: 0.7709133982805174 and parameters: {'num_leaves': 62, 'min_child_samples': 27, 'min_sum_hessian_in_leaf': 1.5883556403079183e-05, 'feature_fraction': 0.508725730792521, 'bagging_fraction': 0.5734077237187469, 'lambda_l1': 0.016483216805916603, 'lambda_l2': 0.29434813057265946}. Best is trial 5 with value: 0.7734238220730583.

Early stopping, best iteration is:
[268]	training's auc: 0.857903	valid_1's auc: 0.772149
Training until validation scores don't improve for 100 rounds

[I 2026-04-15 06:44:37,303] Trial 6 finished with value: 0.7721488033411708 and parameters: {'num_leaves': 77, 'min_child_samples': 190, 'min_sum_hessian_in_leaf': 6.915633686367583e-05, 'feature_fraction': 0.8336361675522375, 'bagging_fraction': 0.9104095250425681, 'lambda_l1': 10.37446875913976, 'lambda_l2': 12.99643024814903}. Best is trial 5 with value: 0.7734238220730583.

Early stopping, best iteration is:
[111]	training's auc: 0.89363	valid_1's auc: 0.764341

[I 2026-04-15 06:44:43,038] Trial 8 finished with value: 0.7643409344914919 and parameters: {'num_leaves': 200, 'min_child_samples': 119, 'min_sum_hessian_in_leaf': 0.0016967937728014245, 'feature_fraction': 0.9513349424653486, 'bagging_fraction': 0.5105953084149066, 'lambda_l1': 0.06764992578559562, 'lambda_l2': 0.3558130659094076}. Best is trial 5 with value: 0.7734238220730583.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[226]	training's auc: 0.886176	valid_1's auc: 0.77112

[I 2026-04-15 06:45:35,035] Trial 7 finished with value: 0.7711201766570244 and parameters: {'num_leaves': 168, 'min_child_samples': 6, 'min_sum_hessian_in_leaf': 1.915678459424718e-05, 'feature_fraction': 0.7661139234165553, 'bagging_fraction': 0.9101560329166364, 'lambda_l1': 14.580962282499435, 'lambda_l2': 6.053616321663842}. Best is trial 5 with value: 0.7734238220730583.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[131]	training's auc: 0.922602	valid_1's auc: 0.764012

[I 2026-04-15 06:47:16,478] Trial 13 finished with value: 0.7640118275307677 and parameters: {'num_leaves': 222, 'min_child_samples': 29, 'min_sum_hessian_in_leaf': 8.47670285232939e-05, 'feature_fraction': 0.5030886354261483, 'bagging_fraction': 0.5364282310868109, 'lambda_l1': 0.2760397332310204, 'lambda_l2': 0.28236255918890335}. Best is trial 5 with value: 0.7734238220730583.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[159]	training's auc: 0.917243	valid_1's auc: 0.770891

[I 2026-04-15 06:47:34,998] Trial 10 finished with value: 0.7708909837823696 and parameters: {'num_leaves': 212, 'min_child_samples': 187, 'min_sum_hessian_in_leaf': 0.0010943962243416016, 'feature_fraction': 0.6676975245163117, 'bagging_fraction': 0.9348225534784236, 'lambda_l1': 3.0482090917635984, 'lambda_l2': 0.8348102030589196}. Best is trial 5 with value: 0.7734238220730583.

Early stopping, best iteration is:
[124]	training's auc: 0.900714	valid_1's auc: 0.765917
Training until validation scores don't improve for 100 rounds

[I 2026-04-15 06:47:45,888] Trial 12 finished with value: 0.76591740542423 and parameters: {'num_leaves': 239, 'min_child_samples': 131, 'min_sum_hessian_in_leaf': 0.0020730598738225884, 'feature_fraction': 0.857740238956826, 'bagging_fraction': 0.5242617498961721, 'lambda_l1': 2.204856533323669, 'lambda_l2': 1.325610636027442}. Best is trial 5 with value: 0.7734238220730583.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[270]	training's auc: 0.866052	valid_1's auc: 0.77237

[I 2026-04-15 06:48:01,840] Trial 11 finished with value: 0.7723699238615976 and parameters: {'num_leaves': 103, 'min_child_samples': 144, 'min_sum_hessian_in_leaf': 0.000191929196475976, 'feature_fraction': 0.5932426791256169, 'bagging_fraction': 0.7319316621975498, 'lambda_l1': 10.44712297324336, 'lambda_l2': 9.632683858913769}. Best is trial 5 with value: 0.7734238220730583.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[676]	training's auc: 0.81203	valid_1's auc: 0.773685

[I 2026-04-15 06:49:05,546] Trial 14 finished with value: 0.7736847664451685 and parameters: {'num_leaves': 10, 'min_child_samples': 151, 'min_sum_hessian_in_leaf': 0.009837900752050276, 'feature_fraction': 0.9612311764062575, 'bagging_fraction': 0.6800953457292709, 'lambda_l1': 0.3890387128111823, 'lambda_l2': 1.20773608617894}. Best is trial 14 with value: 0.7736847664451685.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[653]	training's auc: 0.81275	valid_1's auc: 0.773739

[I 2026-04-15 06:50:45,180] Trial 15 finished with value: 0.7737386616998533 and parameters: {'num_leaves': 11, 'min_child_samples': 192, 'min_sum_hessian_in_leaf': 0.009706307986775776, 'feature_fraction': 0.9676639130944162, 'bagging_fraction': 0.6954830484197465, 'lambda_l1': 2.2325019410718427, 'lambda_l2': 3.192722314411448}. Best is trial 15 with value: 0.7737386616998533.

Early stopping, best iteration is:
[614]	training's auc: 0.812297	valid_1's auc: 0.773303

[I 2026-04-15 06:50:54,188] Trial 16 finished with value: 0.7733032390552894 and parameters: {'num_leaves': 11, 'min_child_samples': 149, 'min_sum_hessian_in_leaf': 0.008370328461805823, 'feature_fraction': 0.9288012586442816, 'bagging_fraction': 0.6724880298630598, 'lambda_l1': 0.4595433145554604, 'lambda_l2': 2.4756383503016375}. Best is trial 15 with value: 0.7737386616998533.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[1025]	training's auc: 0.814085	valid_1's auc: 0.774226

[I 2026-04-15 06:52:30,724] Trial 17 finished with value: 0.7742257317370023 and parameters: {'num_leaves': 8, 'min_child_samples': 157, 'min_sum_hessian_in_leaf': 0.005765024440929317, 'feature_fraction': 0.9567702696134474, 'bagging_fraction': 0.7120379679260175, 'lambda_l1': 0.4354247843656999, 'lambda_l2': 5.462256046387072}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[847]	training's auc: 0.819638	valid_1's auc: 0.772936

[I 2026-04-15 06:53:27,111] Trial 19 finished with value: 0.7729357260703235 and parameters: {'num_leaves': 10, 'min_child_samples': 157, 'min_sum_hessian_in_leaf': 0.005999234246304408, 'feature_fraction': 0.9851194334821199, 'bagging_fraction': 0.6678803803540707, 'lambda_l1': 0.33604816810524796, 'lambda_l2': 2.4284582379291657}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[881]	training's auc: 0.840162	valid_1's auc: 0.773815
Training until validation scores don't improve for 100 rounds

[I 2026-04-15 06:53:38,616] Trial 18 finished with value: 0.7738149643279246 and parameters: {'num_leaves': 15, 'min_child_samples': 142, 'min_sum_hessian_in_leaf': 0.008896884443577327, 'feature_fraction': 0.5907232300404921, 'bagging_fraction': 0.6816890752514541, 'lambda_l1': 0.3196248785576746, 'lambda_l2': 3.3202533621206145}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[376]	training's auc: 0.874195	valid_1's auc: 0.771097

[I 2026-04-15 06:54:06,298] Trial 21 finished with value: 0.7710965830109289 and parameters: {'num_leaves': 44, 'min_child_samples': 160, 'min_sum_hessian_in_leaf': 0.0046898532578960785, 'feature_fraction': 0.9968746252083285, 'bagging_fraction': 0.7198086824861359, 'lambda_l1': 0.14686409735391476, 'lambda_l2': 0.017113238817722812}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[899]	training's auc: 0.81198	valid_1's auc: 0.773732

[I 2026-04-15 06:54:45,338] Trial 20 finished with value: 0.7737316509350163 and parameters: {'num_leaves': 8, 'min_child_samples': 156, 'min_sum_hessian_in_leaf': 0.008014167513235056, 'feature_fraction': 0.9977212393892618, 'bagging_fraction': 0.6954396394634029, 'lambda_l1': 0.226193116193226, 'lambda_l2': 1.9797663814413144}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[338]	training's auc: 0.871244	valid_1's auc: 0.772071

[I 2026-04-15 06:55:54,637] Trial 22 finished with value: 0.7720712859413468 and parameters: {'num_leaves': 52, 'min_child_samples': 165, 'min_sum_hessian_in_leaf': 0.004016523736368577, 'feature_fraction': 0.9020720344000595, 'bagging_fraction': 0.7498599233546039, 'lambda_l1': 0.10977449823794684, 'lambda_l2': 3.623224855005007}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[389]	training's auc: 0.883887	valid_1's auc: 0.77226

[I 2026-04-15 06:56:47,516] Trial 24 finished with value: 0.7722598035553769 and parameters: {'num_leaves': 47, 'min_child_samples': 81, 'min_sum_hessian_in_leaf': 0.0006362293505339895, 'feature_fraction': 0.7253089421409704, 'bagging_fraction': 0.7847104619047915, 'lambda_l1': 0.10855577379533814, 'lambda_l2': 0.010306074003941111}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[305]	training's auc: 0.857726	valid_1's auc: 0.773464

[I 2026-04-15 06:56:55,164] Trial 25 finished with value: 0.7734637349842544 and parameters: {'num_leaves': 46, 'min_child_samples': 85, 'min_sum_hessian_in_leaf': 0.0032072022815848537, 'feature_fraction': 0.9044170322829245, 'bagging_fraction': 0.7784855564015923, 'lambda_l1': 0.0958944706020651, 'lambda_l2': 2.9869132015841413}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[374]	training's auc: 0.844235	valid_1's auc: 0.772378

[I 2026-04-15 06:57:23,363] Trial 23 finished with value: 0.772378224208178 and parameters: {'num_leaves': 45, 'min_child_samples': 200, 'min_sum_hessian_in_leaf': 0.003418688908153731, 'feature_fraction': 0.9041842408952241, 'bagging_fraction': 0.7635709685447958, 'lambda_l1': 0.09587057186530702, 'lambda_l2': 72.4377843710845}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[317]	training's auc: 0.841095	valid_1's auc: 0.772518

[I 2026-04-15 06:57:59,502] Trial 26 finished with value: 0.7725176094702608 and parameters: {'num_leaves': 45, 'min_child_samples': 86, 'min_sum_hessian_in_leaf': 0.0033993186203533786, 'feature_fraction': 0.9045951934987997, 'bagging_fraction': 0.7810963860123284, 'lambda_l1': 0.05168728072444253, 'lambda_l2': 40.29415168954216}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[233]	training's auc: 0.864222	valid_1's auc: 0.772559

[I 2026-04-15 06:59:09,314] Trial 27 finished with value: 0.7725588048384394 and parameters: {'num_leaves': 89, 'min_child_samples': 129, 'min_sum_hessian_in_leaf': 0.000672746191821992, 'feature_fraction': 0.7126428876558836, 'bagging_fraction': 0.7756966832181005, 'lambda_l1': 0.03640899713127174, 'lambda_l2': 25.63823302757686}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[290]	training's auc: 0.864634	valid_1's auc: 0.770706

[I 2026-04-15 07:00:20,712] Trial 29 finished with value: 0.7707063277888087 and parameters: {'num_leaves': 84, 'min_child_samples': 196, 'min_sum_hessian_in_leaf': 0.0005307569923622851, 'feature_fraction': 0.5970353961224848, 'bagging_fraction': 0.6307767173328455, 'lambda_l1': 2.007959497634328, 'lambda_l2': 26.94183286220335}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[211]	training's auc: 0.870881	valid_1's auc: 0.770233

[I 2026-04-15 07:00:46,942] Trial 31 finished with value: 0.7702325276190469 and parameters: {'num_leaves': 87, 'min_child_samples': 131, 'min_sum_hessian_in_leaf': 0.0005761149852791187, 'feature_fraction': 0.56185135181172, 'bagging_fraction': 0.6255357082928953, 'lambda_l1': 1.6678008514118758, 'lambda_l2': 0.6308529161958661}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[275]	training's auc: 0.86558	valid_1's auc: 0.771824

[I 2026-04-15 07:00:53,362] Trial 30 finished with value: 0.7718239890489573 and parameters: {'num_leaves': 86, 'min_child_samples': 130, 'min_sum_hessian_in_leaf': 0.0006935328964782883, 'feature_fraction': 0.5618396434760715, 'bagging_fraction': 0.6195521105169377, 'lambda_l1': 0.04103555802998952, 'lambda_l2': 26.685289089025883}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[346]	training's auc: 0.907259	valid_1's auc: 0.77131

[I 2026-04-15 07:01:15,888] Trial 28 finished with value: 0.7713098377951971 and parameters: {'num_leaves': 103, 'min_child_samples': 199, 'min_sum_hessian_in_leaf': 0.002733787254716853, 'feature_fraction': 0.9013995873855508, 'bagging_fraction': 0.7905698903869224, 'lambda_l1': 0.039697242669865476, 'lambda_l2': 27.86766824702661}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[333]	training's auc: 0.82685	valid_1's auc: 0.771528

[I 2026-04-15 07:02:47,215] Trial 33 finished with value: 0.771527823420778 and parameters: {'num_leaves': 26, 'min_child_samples': 173, 'min_sum_hessian_in_leaf': 0.0018070887210832438, 'feature_fraction': 0.8120921323497402, 'bagging_fraction': 0.5744439924980638, 'lambda_l1': 0.6772823480213751, 'lambda_l2': 0.7643792494764627}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[590]	training's auc: 0.861057	valid_1's auc: 0.77327

[I 2026-04-15 07:03:46,265] Trial 32 finished with value: 0.7732703547208328 and parameters: {'num_leaves': 29, 'min_child_samples': 108, 'min_sum_hessian_in_leaf': 0.0018240435411257148, 'feature_fraction': 0.563601666236348, 'bagging_fraction': 0.6239146979381542, 'lambda_l1': 2.14013404287789, 'lambda_l2': 0.7537540618977597}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[405]	training's auc: 0.828619	valid_1's auc: 0.773255

[I 2026-04-15 07:03:53,398] Trial 34 finished with value: 0.7732553891603244 and parameters: {'num_leaves': 26, 'min_child_samples': 172, 'min_sum_hessian_in_leaf': 0.0018805178622289264, 'feature_fraction': 0.8030304786397079, 'bagging_fraction': 0.7032511068377169, 'lambda_l1': 0.6691342255224128, 'lambda_l2': 14.456492502149889}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[493]	training's auc: 0.844817	valid_1's auc: 0.772569
Early stopping, best iteration is:
[485]	training's auc: 0.833203	valid_1's auc: 0.773091

[I 2026-04-15 07:04:34,897] Trial 35 finished with value: 0.7725691642409528 and parameters: {'num_leaves': 26, 'min_child_samples': 172, 'min_sum_hessian_in_leaf': 0.005712962214082345, 'feature_fraction': 0.9587242715853829, 'bagging_fraction': 0.7131474767103273, 'lambda_l1': 0.6371885215136599, 'lambda_l2': 5.299985284140572}. Best is trial 17 with value: 0.7742257317370023.
[I 2026-04-15 07:04:35,501] Trial 36 finished with value: 0.7730911883556325 and parameters: {'num_leaves': 24, 'min_child_samples': 173, 'min_sum_hessian_in_leaf': 0.006137457435385292, 'feature_fraction': 0.788911612688711, 'bagging_fraction': 0.7120684043226857, 'lambda_l1': 0.7019972884030222, 'lambda_l2': 12.753518775613914}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[536]	training's auc: 0.85419	valid_1's auc: 0.772796

[I 2026-04-15 07:06:09,315] Trial 37 finished with value: 0.7727962980596746 and parameters: {'num_leaves': 26, 'min_child_samples': 171, 'min_sum_hessian_in_leaf': 0.006187088280032267, 'feature_fraction': 0.9591415296618914, 'bagging_fraction': 0.7140127683350495, 'lambda_l1': 0.1867540025570864, 'lambda_l2': 1.68058353256811}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[403]	training's auc: 0.829174	valid_1's auc: 0.772568

[I 2026-04-15 07:06:41,021] Trial 38 finished with value: 0.7725682202101185 and parameters: {'num_leaves': 25, 'min_child_samples': 176, 'min_sum_hessian_in_leaf': 0.0059261059225485056, 'feature_fraction': 0.959080968049108, 'bagging_fraction': 0.7092725030742059, 'lambda_l1': 0.23294084881830385, 'lambda_l2': 13.57772930029369}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[254]	training's auc: 0.866094	valid_1's auc: 0.772607

[I 2026-04-15 07:06:48,111] Trial 39 finished with value: 0.7726073529599838 and parameters: {'num_leaves': 64, 'min_child_samples': 142, 'min_sum_hessian_in_leaf': 0.006548681824489003, 'feature_fraction': 0.9657611947186762, 'bagging_fraction': 0.8470485222494694, 'lambda_l1': 0.1892209739295708, 'lambda_l2': 5.357576515011831}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[250]	training's auc: 0.866425	valid_1's auc: 0.772124

[I 2026-04-15 07:07:17,963] Trial 40 finished with value: 0.7721239379252347 and parameters: {'num_leaves': 60, 'min_child_samples': 141, 'min_sum_hessian_in_leaf': 0.00834033400997797, 'feature_fraction': 0.996495837055482, 'bagging_fraction': 0.8312956222780887, 'lambda_l1': 0.2044455743228684, 'lambda_l2': 1.623640488989966}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[324]	training's auc: 0.884299	valid_1's auc: 0.77124
Training until validation scores don't improve for 100 rounds

[I 2026-04-15 07:07:31,035] Trial 41 finished with value: 0.7712403321891323 and parameters: {'num_leaves': 60, 'min_child_samples': 60, 'min_sum_hessian_in_leaf': 0.006736526693694041, 'feature_fraction': 0.8754621345063193, 'bagging_fraction': 0.6521023254974296, 'lambda_l1': 0.17654642345713367, 'lambda_l2': 1.777879431601828}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[149]	training's auc: 0.872252	valid_1's auc: 0.768639

[I 2026-04-15 07:09:31,903] Trial 44 finished with value: 0.7686389394479742 and parameters: {'num_leaves': 145, 'min_child_samples': 53, 'min_sum_hessian_in_leaf': 3.46627647013196e-05, 'feature_fraction': 0.8566213758531461, 'bagging_fraction': 0.6618083124639978, 'lambda_l1': 6.121238132043906, 'lambda_l2': 0.12269179013953276}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[250]	training's auc: 0.874032	valid_1's auc: 0.771922

[I 2026-04-15 07:09:47,129] Trial 43 finished with value: 0.7719222074419055 and parameters: {'num_leaves': 67, 'min_child_samples': 142, 'min_sum_hessian_in_leaf': 0.0011725507235158148, 'feature_fraction': 0.8551170490773137, 'bagging_fraction': 0.81723401742794, 'lambda_l1': 1.3323834987254422, 'lambda_l2': 0.17352552066479374}. Best is trial 17 with value: 0.7742257317370023.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[393]	training's auc: 0.881171	valid_1's auc: 0.772029

[I 2026-04-15 07:10:22,975] Trial 42 finished with value: 0.7720289114252205 and parameters: {'num_leaves': 62, 'min_child_samples': 142, 'min_sum_hessian_in_leaf': 0.007465992183246566, 'feature_fraction': 0.8591684420633448, 'bagging_fraction': 0.8277462719239204, 'lambda_l1': 5.523003977438706, 'lambda_l2': 4.787970724127143}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[688]	training's auc: 0.812759	valid_1's auc: 0.773842
Early stopping, best iteration is:
[554]	training's auc: 0.827165	valid_1's auc: 0.772502
Training until validation scores don't improve for 100 rounds

[I 2026-04-15 07:10:33,608] Trial 45 finished with value: 0.7738417961779006 and parameters: {'num_leaves': 10, 'min_child_samples': 154, 'min_sum_hessian_in_leaf': 0.008943139315051307, 'feature_fraction': 0.8638547747217152, 'bagging_fraction': 0.6723650511120048, 'lambda_l1': 1.243067812345208, 'lambda_l2': 0.13578650941298737}. Best is trial 17 with value: 0.7742257317370023.
[I 2026-04-15 07:10:36,913] Trial 46 finished with value: 0.7725024408540636 and parameters: {'num_leaves': 16, 'min_child_samples': 152, 'min_sum_hessian_in_leaf': 0.009616586501926818, 'feature_fraction': 0.9337132956217485, 'bagging_fraction': 0.6793003179949798, 'lambda_l1': 1.2080606576267277, 'lambda_l2': 0.46374505560353446}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[657]	training's auc: 0.806956	valid_1's auc: 0.773413

[I 2026-04-15 07:11:51,086] Trial 47 finished with value: 0.773413476920067 and parameters: {'num_leaves': 9, 'min_child_samples': 116, 'min_sum_hessian_in_leaf': 0.009530498930968445, 'feature_fraction': 0.933492683901402, 'bagging_fraction': 0.6873946392694448, 'lambda_l1': 1.2550135351656306, 'lambda_l2': 0.4915794113791488}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[566]	training's auc: 0.825277	valid_1's auc: 0.773593

[I 2026-04-15 07:11:57,372] Trial 48 finished with value: 0.773592839216195 and parameters: {'num_leaves': 15, 'min_child_samples': 154, 'min_sum_hessian_in_leaf': 0.009935689504316435, 'feature_fraction': 0.9321540152884978, 'bagging_fraction': 0.6842601923999949, 'lambda_l1': 0.4061659994904158, 'lambda_l2': 0.45565682113636496}. Best is trial 17 with value: 0.7742257317370023.

Early stopping, best iteration is:
[1228]	training's auc: 0.796409	valid_1's auc: 0.772559

[I 2026-04-15 07:12:54,311] Trial 49 finished with value: 0.7725589651455622 and parameters: {'num_leaves': 8, 'min_child_samples': 117, 'min_sum_hessian_in_leaf': 0.009598273912291582, 'feature_fraction': 0.9309998039719244, 'bagging_fraction': 0.6879377687648813, 'lambda_l1': 60.72240933619627, 'lambda_l2': 7.926809404413999}. Best is trial 17 with value: 0.7742257317370023.

In [31]:
#探索結果の確認
trial = study.best_trial
print("acc(best)={:.4f}".format(trial.value))
display(trial.params)

acc(best)=0.7742

{'num_leaves': 8,
 'min_child_samples': 157,
 'min_sum_hessian_in_leaf': 0.005765024440929317,
 'feature_fraction': 0.9567702696134474,
 'bagging_fraction': 0.7120379679260175,
 'lambda_l1': 0.4354247843656999,
 'lambda_l2': 5.462256046387072}

In [32]:
#ベストなハイパーパラメータの取得
params_best = trial.params
params_best.update(params_base)
display(params_best)

{'num_leaves': 8,
 'min_child_samples': 157,
 'min_sum_hessian_in_leaf': 0.005765024440929317,
 'feature_fraction': 0.9567702696134474,
 'bagging_fraction': 0.7120379679260175,
 'lambda_l1': 0.4354247843656999,
 'lambda_l2': 5.462256046387072,
 'boosting_type': 'gbdt',
 'objective': 'binary',
 'metric': 'auc',
 'verbosity': -1,
 'learning_rate': 0.05,
 'n_estimators': 100000,
 'bagging_freq': 1,
 'random_state': 123}

In [33]:
#ベストなハイパーパラメータを用いたモデル学習
train_oof, imp, metrics = train_lgb(x_train,
                                    y_train,
                                    id_train,
                                    list_nfold=[0,1,2,3,4],
                                    n_splits=5,
                                    params=params_best,
                                   )

-------------------- 0 --------------------
(246008, 162) (61503, 162)
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.764297	valid_1's auc: 0.758243
[200]	training's auc: 0.77648	valid_1's auc: 0.766817
[300]	training's auc: 0.783805	valid_1's auc: 0.770341
[400]	training's auc: 0.789532	valid_1's auc: 0.772113
[500]	training's auc: 0.794209	valid_1's auc: 0.77271
[600]	training's auc: 0.798575	valid_1's auc: 0.773316
[700]	training's auc: 0.802503	valid_1's auc: 0.773649
[800]	training's auc: 0.80619	valid_1's auc: 0.773801
[900]	training's auc: 0.809686	valid_1's auc: 0.774036
[1000]	training's auc: 0.813138	valid_1's auc: 0.774189
[1100]	training's auc: 0.816444	valid_1's auc: 0.774146
Early stopping, best iteration is:
[1025]	training's auc: 0.814085	valid_1's auc: 0.774226
[auc] tr:0.8141, va:0.7742
-------------------- 1 --------------------
(246009, 162) (61502, 162)
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.763801	valid_1's auc: 0.759884
[200]	training's auc: 0.776134	valid_1's auc: 0.769152
[300]	training's auc: 0.783478	valid_1's auc: 0.772784
[400]	training's auc: 0.7892	valid_1's auc: 0.774917
[500]	training's auc: 0.793966	valid_1's auc: 0.776041
[600]	training's auc: 0.798377	valid_1's auc: 0.777092
[700]	training's auc: 0.802441	valid_1's auc: 0.777626
[800]	training's auc: 0.806109	valid_1's auc: 0.777849
[900]	training's auc: 0.809733	valid_1's auc: 0.777915
[1000]	training's auc: 0.81297	valid_1's auc: 0.778085
[1100]	training's auc: 0.816189	valid_1's auc: 0.778281
[1200]	training's auc: 0.819353	valid_1's auc: 0.778428
[1300]	training's auc: 0.822217	valid_1's auc: 0.778393
Early stopping, best iteration is:
[1236]	training's auc: 0.820391	valid_1's auc: 0.778532
[auc] tr:0.8204, va:0.7785
-------------------- 2 --------------------
(246009, 162) (61502, 162)
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.763934	valid_1's auc: 0.76182
[200]	training's auc: 0.77588	valid_1's auc: 0.768499
[300]	training's auc: 0.783169	valid_1's auc: 0.771321
[400]	training's auc: 0.788954	valid_1's auc: 0.77314
[500]	training's auc: 0.793669	valid_1's auc: 0.774092
[600]	training's auc: 0.79814	valid_1's auc: 0.774825
[700]	training's auc: 0.802327	valid_1's auc: 0.775183
[800]	training's auc: 0.806423	valid_1's auc: 0.775741
[900]	training's auc: 0.809859	valid_1's auc: 0.775823
[1000]	training's auc: 0.813538	valid_1's auc: 0.776137
[1100]	training's auc: 0.816663	valid_1's auc: 0.776274
Early stopping, best iteration is:
[1075]	training's auc: 0.815877	valid_1's auc: 0.776393
[auc] tr:0.8159, va:0.7764
-------------------- 3 --------------------
(246009, 162) (61502, 162)
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.763572	valid_1's auc: 0.757287
[200]	training's auc: 0.775986	valid_1's auc: 0.765745
[300]	training's auc: 0.783596	valid_1's auc: 0.769086
[400]	training's auc: 0.789441	valid_1's auc: 0.771141
[500]	training's auc: 0.794298	valid_1's auc: 0.772251
[600]	training's auc: 0.79879	valid_1's auc: 0.772816
[700]	training's auc: 0.802754	valid_1's auc: 0.773047
[800]	training's auc: 0.806504	valid_1's auc: 0.773272
[900]	training's auc: 0.810104	valid_1's auc: 0.773382
[1000]	training's auc: 0.813729	valid_1's auc: 0.773444
[1100]	training's auc: 0.816905	valid_1's auc: 0.773246
Early stopping, best iteration is:
[1006]	training's auc: 0.813907	valid_1's auc: 0.77348
[auc] tr:0.8139, va:0.7735
-------------------- 4 --------------------
(246009, 162) (61502, 162)
Training until validation scores don't improve for 100 rounds
[100]	training's auc: 0.765228	valid_1's auc: 0.754288
[200]	training's auc: 0.777302	valid_1's auc: 0.761955
[300]	training's auc: 0.784774	valid_1's auc: 0.76535
[400]	training's auc: 0.79073	valid_1's auc: 0.767251
[500]	training's auc: 0.795593	valid_1's auc: 0.768472
[600]	training's auc: 0.800011	valid_1's auc: 0.769056
[700]	training's auc: 0.803935	valid_1's auc: 0.769264
[800]	training's auc: 0.807736	valid_1's auc: 0.769522
[900]	training's auc: 0.811503	valid_1's auc: 0.769602
Early stopping, best iteration is:
[893]	training's auc: 0.811241	valid_1's auc: 0.769652
[auc] tr:0.8112, va:0.7697
-------------------- result --------------------
[[0.         0.81408477 0.77422573]
 [1.         0.82039119 0.77853163]
 [2.         0.81587687 0.77639302]
 [3.         0.81390702 0.77348025]
 [4.         0.81124146 0.76965201]]
[cv] tr:0.8151+-0.0030, va:0.7745+-0.0030
[oof] 0.7744

In [34]:
#推論データセット作成とモデル推論
# 推論用のデータセット作成
x_test = df_test.drop(columns=["SK_ID_CURR"])
id_test = df_test[["SK_ID_CURR"]]

# カテゴリ変数をcategory型へ変換
for col in x_test.columns:
    if x_test[col].dtype=="O":
        x_test[col] = x_test[col].astype("category")

# predict
test_pred = predict_lgb(x_test,
                        id_test,
                        list_nfold=[0,1,2,3,4],
                       )

# make submission-file
df_submit = test_pred.rename(columns={"pred":"TARGET"})
print(df_submit.shape)
display(df_submit.head())
df_submit.to_csv("submission_HyperParameterTuning.csv", index=None)

-------------------- 0 --------------------
-------------------- 1 --------------------
-------------------- 2 --------------------
-------------------- 3 --------------------
-------------------- 4 --------------------
Done.
(48744, 2)

   SK_ID_CURR    TARGET
0      100001  0.040158
1      100005  0.128304
2      100013  0.024273
3      100028  0.050033
4      100038  0.194675